//most things here attached to pre defined sectors
//so direct copypasting can, and would, cause problems
class test_grounds_event : eventhandler
{

private void grounds_freeze_actor(actor a)
{
    if(a)
    {
        a.tics = -1;
        a.bdormant = true;
    }
}

private void grounds_init_monsters()
{
    actor a = actor.spawn("arachnotron", (-1234, 2381, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("cyberdemon", (-1408, 2368, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("fatso", (-1621, 2361, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("painelemental", (-1792, 2304, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("cacodemon", (-1928, 2281, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("demon", (-2112, 2176, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("hellknight", (-2180, 2090, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("baronofhell", (-2242, 2000, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("archvile", (-2304, 1856, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("doomimp", (-2313, 1726, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("revenant", (-2336, 1632, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("lostsoul", (-2340, 1519, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("spidermastermind", (-2464, 1312, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("chaingunguy", (-2331, 1070, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("shotgunguy", (-2316, 947, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("zombieman", (-2300, 818, 80) );
    grounds_freeze_actor(a);

    a = actor.spawn("wolfensteinss", (-2269, 688, 80) );
    grounds_freeze_actor(a);
}

//ammo and backpack counts as weapons
private void grounds_init_weapons()
{
    actor.spawn("chainsaw", (232, 905, 40) );
    actor.spawn("pistol", (122, 890, 40) );
    actor.spawn("shotgun", (22, 912, 40) );
    actor.spawn("supershotgun", (-67, 958, 40) );
    actor.spawn("chaingun", (-133, 1042, 40) );
    actor.spawn("rocketlauncher", (-164, 1136, 40) );
    actor.spawn("plasmarifle", (-167, 1246, 40) );
    actor.spawn("bfg9000", (-131, 1338, 40) );

    actor.spawn("clip", (-60, 1418, 40) );
    actor.spawn("clipbox", (32, 1469, 40) );
    actor.spawn("shell", (118, 1486, 40) );
    actor.spawn("shellbox", (225, 1468, 40) );
    actor.spawn("rocketammo", (313, 1415, 40) );

    actor.spawn("rocketbox", (378, 1337, 40) );
    actor.spawn("cell", (416, 1243, 40) );
    actor.spawn("cellpack", (412, 1134, 40) );
    actor.spawn("backpack", (382, 1040, 40) );
}

private void grounds_init_items()
{
    actor.spawn("armorbonus", (768, 64, 40) );
    actor.spawn("greenarmor", (864, -32, 40) );
    actor.spawn("bluearmor", (960, -128, 40) );
    actor.spawn("healthbonus", (1056, -224, 40) );
    actor.spawn("stimpack", (1152, 320, 40) );
    actor.spawn("medikit", (1248, -416, 40) );
    actor.spawn("berserk", (1344, -512, 40) );
    actor.spawn("megasphere", (1024, 320, 40) );
    actor.spawn("allmap", (1120, 224, 40) );
    actor.spawn("radsuit", (1216, 128, 40) );
    actor.spawn("infrared", (1312, 32, 40) );
    actor.spawn("invulnerabilitysphere", (1408, -64, 40) );
    actor.spawn("blursphere", (1504, -160, 40) );
    actor.spawn("soulsphere", (1600, -256, 40) );
    
}

override void worldloaded(worldevent e)
{
    grounds_init_monsters();
    grounds_init_weapons();
    grounds_init_items();
}

private void grounds_spawn_item(class<actor> type = null, int pos = 0)
{
    if(type && pos)
    {
        vector3 p = (0, 0, 0);
        switch(pos)
        {
            default:
            case 0:
            break;

            case 1:
                p = (128, 1184, 32);
            break;

            case 2:
                p = (1120, -32, 32);
            break;
        }
        actor.spawn(type, p, ALLOW_REPLACE);
    }
}

private void grounds_spawn_monster(class<actor> type = null)
{
    if(type)
    {
        if(type == 'demon' && random[grounds_monster](0, 1) == 1)
            type = 'spectre';

        actor.spawn(type, (-1920, 1792, -32), ALLOW_REPLACE);
    }
}

override void WorldLinePreActivated(WorldEvent e)
{
    //pure magic numbers here ripped directly from map editor
    if(e.ActivatedLine)
    {
        //console.printf("activated line %i", e.ActivatedLine.index() );
        //which actor should spawn
        class<actor> acc = null;
        //and on what position
        //1 weapons
        //2 items
        //3 monsters
        int spawn_type = 0;

        switch(e.ActivatedLine.index() )
        {
            case 0:
            default:
            break;

            //weapons here
            case 253:
                acc = "chainsaw";
                spawn_type = 1;
            break;
    
            case 237:
                acc = "pistol";
                spawn_type = 1;
            break;
            case 241:
                acc = "shotgun";
                spawn_type = 1;
            break;
            case 244:
                acc = "supershotgun";
                spawn_type = 1;
            break;
            case 247:
                acc = "chaingun";
                spawn_type = 1;
            break;
            case 249:
                acc = "rocketlauncher";
                spawn_type = 1;
            break;
            case 256:
                acc = "plasmarifle";
                spawn_type = 1;
            break;
            case 259:
                acc = "bfg9000";
                spawn_type = 1;
            break;
            case 262:
                acc = "clip";
                spawn_type = 1;
            break;
            case 265:
                acc = "clipbox";
                spawn_type = 1;
            break;
            case 267:
                acc = "shell";
                spawn_type = 1;
            break;
            case 271:
                acc = "shellbox";
                spawn_type = 1;
            break;
            case 273:
                acc = "rocketammo";
                spawn_type = 1;
            break;
            case 277:
                acc = "rocketbox";
                spawn_type = 1;
            break;
            case 279:
                acc = "cell";
                spawn_type = 1;
            break;
            case 282:
                acc = "cellpack";
                spawn_type = 1;
            break;
            case 285:
                acc = "backpack";
                spawn_type = 1;
            break;

        
            case 159:
                acc = "armorbonus";
                spawn_type = 2;
            break;

            case 164:
                acc = "greenarmor";
                spawn_type = 2;
            break;
            case 169:
                acc = "bluearmor";
                spawn_type = 2;
            break;
            case 174:
                acc = "healthbonus";
                spawn_type = 2;
            break;
            case 179:
                acc = "stimpack";
                spawn_type = 2;
            break;
            case 184:
                acc = "medikit";
                spawn_type = 2;
            break;
            case 189:
                acc = "berserk";
                spawn_type = 2;
            break;
            case 149:
                acc = "soulsphere";
                spawn_type = 2;
            break;
            case 144:
                acc = "blursphere";
                spawn_type = 2;
            break;
            case 139:
                acc = "invulnerabilitysphere";
                spawn_type = 2;
            break;
            case 134:
                acc = "infrared";
                spawn_type = 2;
            break;
            case 129:
                acc = "radsuit";
                spawn_type = 2;
            break;
            case 124:
                acc = "allmap";
                spawn_type = 2;
            break;
            case 119:
                acc = "megasphere";
                spawn_type = 2;
            break;


            case 783:
                acc = "arachnotron";
                spawn_type = 3;
            break;
            case 780:
                acc = "cyberdemon";
                spawn_type = 3;
            break;
            case 787:
                acc = "fatso";
                spawn_type = 3;
            break;
            case 793:
            case 79:
               acc = "painelemental";
                spawn_type = 3;
            break;
            case 798:
                acc = "cacodemon";
                spawn_type = 3;
            break;
            case 802:
                acc = "demon";
                spawn_type = 3;
            break;
            case 828:
                acc = "hellknight";
                spawn_type = 3;
            break;
            case 805:
                acc = "baronofhell";
                spawn_type = 3;
            break;
            case 808:
                acc = "archvile";
                spawn_type = 3;
            break;
            case 812:
                acc = "doomimp";
                spawn_type = 3;
            break;
            case 817:
                acc = "revenant";
                spawn_type = 3;
            break;
            case 822:
                acc = "lostsoul";
                spawn_type = 3;
            break;
            case 773:
                acc = "spidermastermind";
                spawn_type = 3;
            break;
            case 832:
                acc = "chaingunguy";
                spawn_type = 3;
            break;
            case 837:
                acc = "shotgunguy";
                spawn_type = 3;
            break;
            case 759:
            case 756:
                acc = "zombieman";
                spawn_type = 3;
            break;
            case 748:
            case 749:
               acc = "wolfensteinss";
                spawn_type = 3;
            break;
       }

        if(acc && spawn_type)
        {
            if(spawn_type == 1 || spawn_type == 2)
            grounds_spawn_item(acc, spawn_type);

            else
                grounds_spawn_monster(acc);
        }

    }
}

}